-- ============================================================
-- Supabase Database Seed File
-- Generated on: 2026-06-27T09:19:25.238Z
-- ============================================================

-- ─── settings seed ──────────────────────────────────────────
INSERT INTO settings (id, value)
VALUES (1, '{"storeName":"Para Officinal S.A","freeShippingThreshold":600,"shippingFee":35,"quizDiscountPercent":15,"coupons":[{"code":"BEAUTY10","discountPercent":10,"freeShipping":false,"isActive":true},{"code":"CLINICAL15","discountPercent":15,"freeShipping":false,"isActive":true},{"code":"FREESHIP","discountPercent":0,"freeShipping":true,"isActive":true},{"code":"GIFTGLOW","discountPercent":0,"freeShipping":false,"giftItem":"Masque Hydra-Glow Offert","isActive":true}]}')
ON CONFLICT (id) DO UPDATE SET value = EXCLUDED.value;

-- ─── products seed ──────────────────────────────────────────
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  1,
  'Garnier Super UV Cooling Gel Solaire 30ml',
  'Garnier Super UV Cooling Gel 30ml',
  'Garnier Super UV Gel Solaire Rafraîchissant 30ml',
  'Garnier',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  49.00,
  59.00,
  'garnier',
  '{"visage","solaire","homme","sport"}'::TEXT[],
  4.8,
  14,
  'Ce fluide photoprotecteur haute performance offre une très haute protection SPF 50+ contre les rayonnements UVA et UVB, prévenant activement le photovieillissement prématuré. Sa formule intègre un agent cryogène assurant un rafraîchissement épidermique immédiat de la barrière cutanée. Sa texture hydro-dispersible pénètre instantanément sans laisser de film lipidique occlusif ou de traces blanchâtres.',
  'Aqua / Water, Alcohol Denat., Diisopropyl Sebacate, Silica, Isopropyl Myristate, Ethylhexyl Salicylate, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyl Methoxydibenzoylmethane, Glycerin, Menthol, Tocopherol, Caprylyl Glycol, Hydrolyzed Rice Protein, Hydroxyethylcellulose, Trisodium Ethylenediamine Disuccinate.',
  'Appliquer uniformément sur l''ensemble du visage et du cou vingt minutes avant l''exposition solaire. Renouveler l''application toutes les deux heures pour maintenir l''indice de photoprotection, particulièrement après sudation ou baignade.',
  100,
  'SKU-GARNIER-001',
  29,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  2,
  'Garnier Super UV Invisible Serum Sunscreen SPF 50',
  'Garnier Super UV Invisible Serum Sunscreen SPF 50',
  'Garnier Sérum Solaire Invisible Super UV SPF 50',
  'Garnier',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  69.00,
  89.00,
  'garnier',
  '{"visage","solaire"}'::TEXT[],
  4.9,
  28,
  'Formulation dermo-cosmétique avancée sous forme de sérum ultra-fluide offrant une photoprotection SPF 50+ PA++++. Conçu pour lutter contre les dommages cellulaires profonds induits par les rayons UVA longs, ce sérum intègre des agents hydratants biomimétiques qui renforcent l''intégrité de la barrière épidermique. Offre un fini parfaitement imperceptible et mat, constituant une excellente base de préparation cutanée avant maquillage.',
  'Aqua / Water, Alcohol Denat., Diisopropyl Sebacate, Silica, Isopropyl Myristate, Ethylhexyl Salicylate, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyl Methoxydibenzoylmethane, Glycerin, C12-22 Alkyl Acrylate/Hydroxyethylacrylate Copolymer, Drometrizole Trisiloxane, Perlite, Caprylyl Glycol, Tocopherol.',
  'Agiter vigoureusement le flacon pour homogénéiser la formule. Appliquer quotidiennement le matin comme dernière étape du protocole de soin. Étaler délicatement de l''intérieur vers l''extérieur du visage.',
  100,
  'SKU-GARNIER-001',
  29,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  3,
  'Garnier Fast Bright Booster Serum 30ml',
  'Garnier Fast Bright Serum 30ml',
  'Garnier Sérum Booster Éclat Rapide Vitamine C 30ml',
  'Garnier',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  119.00,
  139.00,
  'garnier',
  '{"visage"}'::TEXT[],
  4.6,
  19,
  'Sérum correcteur hautement concentré en Vitamine C dermo-active, enrichi en Niacinamide sébo-régulateur et en Acide Salicylique exfoliant. Ce soin cible de manière sélective l''hyperpigmentation et les désordres pigmentaires pour lisser le grain de peau et restaurer la luminosité naturelle du teint tout en favorisant le renouvellement cellulaire.',
  'Aqua / Water, Glycerin, Alcohol, Dipropylene Glycol, Butylene Glycol, Niacinamide, PEG/PPG/Polybutylene Glycol-8/5/3 Glycerin, 3-O-Ethyl Ascorbic Acid (Vitamin C), Salicylic Acid, Citrus Limon Fruit Extract / Lemon Fruit Extract, Phenoxyethanol, Sodium Hyaluronate, Tocopheryl Acetate, Linalool, Limonene, Parfum.',
  'Appliquer matin et soir trois à quatre gouttes sur un épiderme préalablement purifié. Effectuer de légers tapotements pour stimuler la micro-circulation. L''application d''un écran solaire SPF de haute protection est requise en journée.',
  100,
  'SKU-GARNIER-003',
  71,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  4,
  'Garnier Super UV Invisible Air-Mist Sunscreen 75ml',
  'Garnier Super UV Invisible Air-Mist Sunscreen 75ml',
  'Garnier Brume Solaire Protectrice Super UV Invisible 75ml',
  'Garnier',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  139.00,
  169.00,
  'garnier',
  '{"visage","solaire","corps","homme","sport"}'::TEXT[],
  4.7,
  22,
  'Brume de photoprotection à diffusion micro-aérée garantissant un bouclier invisible SPF 50 contre les rayonnements ultraviolets et le dépôt de particules polluantes. Sa formule légère s''adapte parfaitement au rythme urbain et sportif, créant une barrière matifiante non occlusive.',
  'Butane, Aqua / Water, Homosalate, Octocrylene, Glycerin, Dimethicone, Ethylhexyl Salicylate, Dicaprylyl Carbonate, Nylon-12, Methyl Methacrylate Crosspolymer, Cyclohexasiloxane, d-Limonene, Benzyl Salicylate, Tocopherol, Phenoxyethanol, Caprylyl Glycol, Parfum / Fragrance.',
  'Agiter énergiquement avant emploi. Fermer les yeux et la bouche. Vaporiser de manière homogène à une distance minimale de 15 centimètres sur l''ensemble du visage et du cou. Renouveler au cours de la journée.',
  100,
  'SKU-GARNIER-003',
  71,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  5,
  'Hada Labo Tokyo Absolute Smoothing & Moisturizing Cream 50ml',
  'Hada Labo Tokyo Absolute Smoothing & Moisturizing Cream 50ml',
  'Hada Labo Tokyo Crème Hydratante & Lissante Absolue 50ml',
  'Hada Labo Tokyo',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  209.00,
  259.00,
  'hadalabo',
  '{"visage"}'::TEXT[],
  4.8,
  31,
  'Crème de soin hautement hydratante intégrant le complexe japonais exclusif Super Hyaluronic Acid. Conçue pour restaurer l''homéostasie hydrique de la peau, elle comble de l''intérieur les ridules de déshydratation, améliorant visiblement la texture cutanée. Cette édition inclut un accessoire d''officine (trousse de soin élégante).',
  'Aqua, Glycerin, Dipropylene Glycol, Squalane, Diglycerin, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Acetylated Hyaluronate, Carbomer, Dimethicone, Disodium EDTA, Phytosteryl/Octyldodecyl Lauroyl Glutamate, Methylparaben.',
  'Appliquer matin et soir sur un visage parfaitement propre et tonifié. Effectuer des mouvements d''effleurage doux de bas en haut pour favoriser l''absorption des principes actifs.',
  100,
  'SKU-HADALABOTOKYO-005',
  125,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  6,
  'Hada Labo Tokyo Intense Hydrating Skin-Plump Gel 50ml',
  'Hada Labo Tokyo Intense Hydrating Skin-Plump Gel 50ml',
  'Hada Labo Tokyo Gel-Crème Hydratation & Repulpant Intense 50ml',
  'Hada Labo Tokyo',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  219.00,
  269.00,
  'hadalabo',
  '{"visage","masques"}'::TEXT[],
  4.9,
  44,
  'Formulation hybride avancée associant la légèreté d''un gel-crème et la concentration d''un sérum. Sa formule enrichie en Super Hyaluronic Acid, collagène dermo-assimilable et arginine favorise la régénération cellulaire globale et repulpe l''épiderme fatigué pour un fini éclatant. Livré avec un accessoire de toilette de marque.',
  'Aqua, Butylene Glycol, Glycerin, Hydroxyethyl Urea, Pentylene Glycol, PPG-10 Methyl Glucose Ether, Triethylhexanoin, Ammonium Acryloyldimethyltaurate/VP Copolymer, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Hydrolyzed Collagen, Arginine.',
  'Appliquer généreusement matin et soir sur les zones cibles du visage et du cou. Peut également s''utiliser en masque de nuit en couche plus épaisse pour un traitement réparateur intensif.',
  100,
  'SKU-HADALABOTOKYO-005',
  125,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  7,
  'Hada Labo Tokyo Premium Lotion Intense 7XHA Super Deep Hydrator 150ml',
  'Hada Labo Tokyo Premium Lotion Intense 7XHA Super Deep Hydrator 150ml',
  'Hada Labo Tokyo Premium Lotion Hydratante Intense 7XHA 150ml',
  'Hada Labo Tokyo',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  189.00,
  239.00,
  'hadalabo',
  '{"visage"}'::TEXT[],
  5,
  57,
  'Soin préparateur haut de gamme et pilier de l''hydratation dermatologique japonaise. Cette lotion gélifiée intègre sept formes complémentaires d''acides hyaluroniques de poids moléculaires distincts afin de saturer en eau toutes les couches de l''épiderme, tout en optimisant l''absorption des soins ultérieurs. Livrée avec sa trousse beauté.',
  'Aqua, Glycerin, Butylene Glycol, Pentylene Glycol, Sodium Hyaluronate, Hydrolyzed Sodium Hyaluronate, Sodium Acetylated Hyaluronate, Hydroxypropyltrimonium Hyaluronate, Sodium Hyaluronate Crosspolymer, Hydrolyzed Hyaluronic Acid, Lactococcus/Hyaluronic Acid Ferment Filtrate.',
  'Verser quelques gouttes dans le creux des mains préalablement lavées, puis presser délicatement sur le visage et le cou. Éviter l''utilisation d''un coton pour limiter la perte de formule.',
  100,
  'SKU-HADALABOTOKYO-007',
  113,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  8,
  'Hada Labo Tokyo Wrinkle Reducer Anti-Aging Day Cream 50ml',
  'Hada Labo Tokyo Anti-Aging Day Cream Wrinkle Reducer 50ml',
  'Hada Labo Tokyo Crème de Jour Anti-Âge Réductrice de Rides 50ml',
  'Hada Labo Tokyo',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  229.00,
  279.00,
  'hadalabo',
  '{"visage","homme"}'::TEXT[],
  4.8,
  26,
  'Traitement restructurant ciblant spécifiquement la sénescence cutanée. Sa formule associe le complexe Super Hyaluronic Acid à un palmitate de rétinol stabilisé et à du collagène marin d''une excellente biodisponibilité. Accélère la synthèse d''élastine et de collagène endogène pour regalber l''ovale du visage. Coffret exclusif avec trousse.',
  'Aqua, Glycerin, Butylene Glycol, Caprylic/Capric Triglyceride, Simmondsia Chinensis Seed Oil, Retinyl Palmitate (Retinol), Hydrolyzed Collagen, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Beta-Carotene, Tocopherol, Pentylene Glycol.',
  'Appliquer chaque matin sur l''ensemble du visage, du cou et du décolleté propres. Réaliser des pressions fermes et des mouvements lissants ascendants.',
  100,
  'SKU-HADALABOTOKYO-007',
  113,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  9,
  'Bioderma Photoderm XDefense Ultra Fluide SPF50+ Invisible 40ml',
  'Bioderma Photoderm XDefense Ultra Fluid SPF50+ Invisible 40ml',
  'Bioderma Photoderm XDefense Ultra Fluide SPF50+ Invisible 40ml',
  'Bioderma',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  169.00,
  191.00,
  'offers',
  '{"visage","solaire","sport"}'::TEXT[],
  4.9,
  35,
  'Formulation protectrice brevetée Sun Active Defense offrant une défense biologique contre les altérations causées par le spectre des UVA courts et longs. Sa texture ultra-fluide fusionne parfaitement avec la structure cutanée, laissant un fini imperceptible et non gras. Ce pack d''été comprend un sac cabas exclusif de la marque.',
  'Aqua/Water/Eau, Dicaprylyl Carbonate, Octocrylene, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol [Nano], Butyl Methoxydibenzoylmethane, Glycerin, Methyl Methacrylate Crosspolymer, Ectoin, Mannitol, Xylitol, Rhamnose, Fructooligosaccharides.',
  'Appliquer généreusement sur la zone du visage et du cou avant de s''exposer. Renouveler impérativement l''application après baignade, frottement mécanique ou sudation.',
  100,
  'SKU-BIODERMA-009',
  101,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  10,
  'Embryolisse Lait-Crème Concentré 75ml',
  'Embryolisse Lait-Crème Concentré 75ml',
  'Embryolisse Lait-Crème Concentré 75ml',
  'Embryolisse',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  199.00,
  239.00,
  'offers',
  '{"visage","corps","bebe","masques"}'::TEXT[],
  4.8,
  48,
  'Soin dermatologique polyvalent 6-en-1 de renommée mondiale. Formulé à base d''acides gras essentiels et de vitamines naturelles, il assure simultanément les fonctions de crème hydratante, de base lissante de maquillage, de lait démaquillant physiologique, de masque nourrissant et de soin après-rasage apaisant. Offert dans un coffret exclusif.',
  'Aqua, Paraffinum Liquidum, Stearic Acid, Palmitic Acid, Glyceryl Stearate SE, Triethanolamine, Cera Alba (Beeswax), Cetyl Palmitate, Butyrospermum Parkii (Shea Butter), 1,2-Hexanediol, Caprylyl Glycol, Steareth-10, Polyacrylamide, Aloe Barbadensis Leaf Extract.',
  'Prélever une petite quantité et masser délicatement sur le visage et le cou propres en base ou soin protecteur. Pour l''utiliser en masque réparateur, appliquer en couche épaisse et laisser poser 15 minutes.',
  100,
  'SKU-EMBRYOLISSE-009',
  101,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  11,
  'Nivea Sun Spray Solaire Protecteur & Hydratant SPF50+ 200ml',
  'Nivea Sun Protect & Moisture SPF50+ Spray 200ml',
  'Nivea Sun Spray Solaire Protecteur & Hydratant SPF50+ 200ml',
  'Nivea Sun',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  149.00,
  189.00,
  'offers',
  '{"corps","solaire","homme","sport","bebe"}'::TEXT[],
  4.7,
  17,
  'Brume corporelle de photoprotection combinant des filtres UVA/UVB à large spectre à un complexe hydratant dermo-protecteur 48h. Aide à neutraliser le stress oxydatif induit par le soleil tout en préservant le confort épidermique. Sa formule résiste à l''eau.',
  'Aqua, Homosalate, Glycerin, Alcohol Denat., Butyl Methoxydibenzoylmethane, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Ethylhexyl Salicylate, Dibutyl Adipate, Copernicia Cerifera Cera, Panthenol, Silica, VP/Hexadecene Copolymer, Tocopheryl Acetate.',
  'Agiter vigoureusement avant emploi. Vaporiser généreusement sur les zones du corps avant exposition. Ne pas orienter le spray directement vers les yeux. Répartir uniformément.',
  100,
  'SKU-NIVEASUN-011',
  89,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  12,
  'Maybelline Mascara Lash Sensational Sky High Noir',
  'Maybelline Lash Sensational Sky High Mascara Black',
  'Maybelline Mascara Lash Sensational Sky High Noir',
  'Maybelline',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  119.00,
  149.00,
  'offers',
  '{"maquillage"}'::TEXT[],
  4.8,
  62,
  'Mascara haute définition formulé à base d''extraits de bambou fortifiants et de fibres dermo-compatibles. Sa brosse exclusive Flex Tower épouse parfaitement l''anatomie ciliaire pour allonger intensément sans surcharger ni créer de paquets.',
  'Aqua / Water / Eau, Propylene Glycol, Styrene/Acrylates/Ammonium Methacrylate Copolymer, Polyurethane-35, Cera Alba / Beeswax / Cire Dabeille, Synthetic Fluorphlogopite, Glyceryl Stearate, Cetyl Alcohol, PEG-200 Glycol, Copernicia Cerifera Cera / Carnauba Wax.',
  'Positionner la brosse à la base des cils et étirer vers le haut en effectuant de légers mouvements horizontaux de zigzag. Renouveler l''application pour moduler le volume.',
  100,
  'SKU-MAYBELLINE-011',
  89,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  13,
  'Beauty of Joseon Relief Sun Rice Probiotics SPF 50+',
  'Beauty of Joseon Relief Sun Rice Probiotics SPF 50+',
  'Beauty of Joseon Relief Sun Riz + Probiotiques Écran Solaire SPF 50+',
  'Beauty of Joseon',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  229.00,
  320.00,
  'kbeauty',
  '{"visage","solaire","sport"}'::TEXT[],
  4.9,
  142,
  'Soin photoprotecteur biologique de pointe formulé avec 30% d''extraits de riz et de ferments de céréales (probiotiques). Cet écran assure une haute protection SPF 50+ PA++++ tout en nourrissant et en renforçant activement le microbiome cutané. Sa texture légère, similaire à une crème de jour fondante, pénètre sans fini gras ni effet blanc.',
  'Water, Oryza Sativa (Rice) Extract (30%), Glycerin, Methylpropanediol, Niacinamide, Portulaca Oleracea Extract, Saccharomyces/Rice Ferment Filtrate, Lactobacillus/Pumpkin Ferment Extract, Monascus/Rice Ferment, Adenosine, Silica, Tocopherol.',
  'Appliquer généreusement et de manière uniforme sur le visage et le cou comme dernière étape de votre rituel matinal. Excellente compatibilité avec le maquillage.',
  100,
  'SKU-BEAUTYOFJOSEON-013',
  137,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  14,
  'Anua Niacinamide 10% + TXA 4% Dark Spot Correcting Serum 30ml',
  'Anua Niacinamide 10% + TXA 4% Dark Spot Correcting Serum 30ml',
  'Anua Sérum Correcteur Niacinamide 10% + TXA 4% Anti-Taches 30ml',
  'Anua',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  289.00,
  320.00,
  'kbeauty',
  '{"visage"}'::TEXT[],
  4.8,
  79,
  'Traitement ciblé intensif de l''hyperpigmentation cutanée. Associe synergiquement 10% de Niacinamide et 4% d''Acide Tranexamique (TXA) pour bloquer la synthèse et le transfert mélanique anormal. Idéal pour estomper les marques érythémateuses post-acnéiques et réguler les dysfonctionnements sébacés.',
  'Water, Niacinamide (10%), Tranexamic Acid (4%), Butylene Glycol, Glycerin, Arbutin, 1,2-Hexanediol, Sodium Hyaluronate, Centella Asiatica Extract, Glutathione, Allantoin, Panthenol, Dipotassium Glycyrrhizate, Ethylhexylglycerin.',
  'Appliquer trois à quatre gouttes matin et soir sur un visage propre et tonifié. Tapoter doucement. L''utilisation d''une haute protection solaire en journée est impérative.',
  100,
  'SKU-ANUA-013',
  137,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  15,
  'Anua Heartleaf Pore Control Cleansing Oil 200ml',
  'Anua Heartleaf Pore Control Cleansing Oil 200ml',
  'Anua Huile Nettoyante Régulatrice des Pores Heartleaf 200ml',
  'Anua',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  260.00,
  360.00,
  'kbeauty',
  '{"visage","homme"}'::TEXT[],
  4.9,
  98,
  'Huile démaquillante et purifiante dermo-physiologique formulée à base d''extraits d''Heartleaf (Houttuynia Cordata) pour dissoudre sélectivement les lipides sébacés oxydés, le maquillage résistant et les impuretés microscopiques. Sa formule prévient activement les comédons et apaise les réactions épidermiques.',
  'Ethylhexyl Palmitate, Sorbeth-30 Tetraoleate, Houttuynia Cordata Extract, Simmondsia Chinensis (Jojoba) Seed Oil, Olea Europaea (Olive) Fruit Oil, Vitis Vinifera (Grape) Seed Oil, Macadamia Integrifolia Seed Oil, Tocopherol, Water, Butylene Glycol.',
  'Sur peau et mains sèches, masser délicatement en mouvements circulaires. Émulsionner en ajoutant de l''eau tiède pour former un lait fluide, puis rincer abondamment à l''eau claire.',
  100,
  'SKU-ANUA-015',
  156,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  16,
  'Skin1004 Madagascar Centella Tone Brightening Capsule Ampoule 100ml',
  'Skin1004 Madagascar Centella Tone Brightening Capsule Ampoule 100ml',
  'Skin1004 Madagascar Centella Ampoule Capsule Éclaircissante 100ml',
  'Skin1004',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  269.00,
  370.00,
  'kbeauty',
  '{"visage","masques"}'::TEXT[],
  4.7,
  54,
  'Traitement intensif hautement concentré en extraits purifiés de Centella Asiatica de Madagascar (77%). Intègre la technologie brevetée Madawhite encapsulée, libérant ses agents éclaircissants lors de l''application pour estomper les taches de mélanine et réparer les épidermes sensibilisés.',
  'Centella Asiatica Extract (77%), Butylene Glycol, Niacinamide, Glycerin, 1,2-Hexanediol, Tranexamic Acid, Madecassoside (Capsules), Biosaccharide Gum-1, Ethylhexylglycerin, Xanthan Gum, Citric Acid, Sodium Citrate.',
  'Prélever une dose complète à l''aide de la pipette et appliquer sur le visage préalablement purifié. Masser délicatement pour rompre les capsules actives.',
  100,
  'SKU-SKIN1004-015',
  156,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  17,
  'Skin1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50+ 50ml',
  'Skin1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50+ 50ml',
  'Skin1004 Madagascar Centella Hyalu-Cica Sérum Solaire Water-Fit SPF50+ 50ml',
  'Skin1004',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  209.00,
  320.00,
  'kbeauty',
  '{"visage","solaire"}'::TEXT[],
  5,
  112,
  'Formulation solaire organique de pointe à index SPF 50+ PA++++. Associe de la Centella Asiatica apaisante et de l''acide hyaluronique multi-poids pour hydrater intensément tout en protégeant contre le rayonnement nocif. Sa formule hydro-dispersible ne laisse aucun fini blanc ou résidu.',
  'Water, Centella Asiatica Extract (38%), Glycerin, Didiethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Methylene Bis-Benzotriazolyl Tetramethylbutylphenol, Sodium Hyaluronate, Hyaluronic Acid, Hydrolyzed Hyaluronic Acid.',
  'Appliquer généreusement sur le visage et le cou le matin après le rituel de soin quotidien et avant l''exposition.',
  100,
  'SKU-SKIN1004-017',
  125,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  18,
  'Kérastase Elixir Ultime L''Huile Originale Sublimatrice 100ml',
  'Kerastase Elixir Ultime L''Huile Originale 100ml',
  'Kérastase Elixir Ultime L''Huile Originale Sublimatrice Cheveux 100ml',
  'Kérastase',
  'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  450.00,
  490.00,
  'offers',
  '{"cheveux"}'::TEXT[],
  4.9,
  87,
  'Élixir capillaire d''exception formulé à base d''huiles végétales précieuses (Marula, Camélia et Argan). Restructure intensément la fibre capillaire, scelle les écailles et apporte une brillance et un éclat incomparables tout en assurant une protection thermique.',
  'Cyclopentasiloxane, Dimethiconol, Zea Mays Germ Oil / Corn Germ Oil, Argania Spinosa Kernel Oil, Sclerocarya Birrea Seed Oil, Camellia Oleifera Seed Oil, Pentaclethra Macroloba Seed Oil, Linalool, Alpha-Isomethyl Ionone, Limonene, Geraniol, Parfum / Fragrance.',
  'Répartir une à deux pressions sur cheveux humides ou secs, des mi-longueurs jusqu''aux pointes. Procéder au séchage ou au coiffage.',
  100,
  'SKU-KRASTASE-017',
  125,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  19,
  'Foreo Luna 4 Go Facial Cleansing Brush',
  'Foreo Luna 4 Go Facial Cleansing Brush',
  'Foreo Luna 4 Go Brosse Nettoyante Visage en Silicone Ultra-Hygiénique',
  'Foreo',
  'https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  1290.00,
  1490.00,
  'kbeauty',
  '{"appareils","visage"}'::TEXT[],
  4.8,
  19,
  'Dispositif d''exfoliation et de nettoyage épidermique en silicone de qualité médicale ultra-hygiénique. Émet des pulsations soniques T-Sonic qui désincrustent les impuretés des pores et stimulent la micro-circulation sans irriter la peau.',
  'Silicone médical ultra-hygiénique, sans phtalates ni bisphénol A. 100% étanche. Batterie rechargeable longue durée.',
  'Humidifier le visage et appliquer la mousse nettoyante. Activer l''appareil et effectuer des mouvements circulaires sur l''ensemble du visage durant une minute. Rincer.',
  100,
  'SKU-FOREO-019',
  774,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  20,
  'Beautyblender Original Sponge & Cleanser Set',
  'Beautyblender Original Sponge & Cleanser Set',
  'Beautyblender Kit Éponge Originale & Nettoyant de Teint',
  'BeautyBlender',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  199.00,
  249.00,
  'offers',
  '{"accessoires","maquillage"}'::TEXT[],
  4.7,
  35,
  'Kit d''application professionnel comprenant l''éponge hydrophile brevetée sans latex et un pain de savon nettoyant dermo-protecteur. Permet une répartition homogène des produits de teint pour un fini naturel seconde peau.',
  'Mousse polyuréthane hydrophile de qualité médicale brevetée, sans latex, non allergène et sans parfum.',
  'Humidifier entièrement l''éponge à l''eau, l''essorer fermement, puis prélever et appliquer le fond de teint ou la BB crème par légers tapotements.',
  100,
  'SKU-BEAUTYBLENDER-019',
  774,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  21,
  'Solgar Skin Nails Hair Formula 60 Tablets',
  'Solgar Skin Nails Hair Formula 60 Tablets',
  'Solgar Formule Nutritive Peau Ongles Cheveux 60 Comprimés',
  'Solgar',
  'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1584017911766-d451b3d0e843?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  249.00,
  299.00,
  'offers',
  '{"complements"}'::TEXT[],
  4.8,
  56,
  'Formulation nutritionnelle premium favorisant la synthèse endogène du collagène et de la kératine. Intègre du MSM (source de soufre organique), du zinc dermo-régulateur, de la silice d''algues rouges et de la vitamine C co-facteur de collagène.',
  'MSM (Méthylsulfonylméthane), Silice (Algue rouge L. calcareum), Vitamine C (Acide L-ascorbique), Zinc (Citrate), Cuivre (Glycinate), L-Proline, L-Lysine, Cellulose microcristalline, Acide stéarique végétal, Stéarate de magnésium.',
  'Pour adultes, ingérer deux comprimés par jour au cours d''un repas avec un grand verre d''eau. Ne pas dépasser la posologie recommandée.',
  100,
  'SKU-SOLGAR-021',
  149,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  22,
  'Anua Heartleaf Pore Deep Cleansing Foam 150ml',
  'Anua Heartleaf Pore Deep Cleansing Foam 150ml',
  'Anua Heartleaf Mousse Nettoyante Profonde des Pores 150ml',
  'Anua',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=320&auto=format&fit=crop","https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=320&auto=format&fit=crop"}'::TEXT[],
  179.00,
  220.00,
  'kbeauty',
  '{"visage","kbeauty"}'::TEXT[],
  4.8,
  42,
  'Mousse nettoyante profonde formulée à base de poudre d''Heartleaf (3 000 ppm) et d''acide salicylique. Purifie les comédons, élimine l''excès de sébum oxydé et régule l''apparition de micro-kystes tout en respectant le pH physiologique de la peau. Parfait en seconde étape de nettoyage.',
  'Houttuynia Cordata Extract, Glycerin, Sodium Cocoyl Glycinate, Water, Sodium Lauroyl Glutamate, Methylpropanediol, Sodium Cocoyl Isethionate, 1,2-Hexanediol, Salicylic Acid, Quercetin.',
  'Faire mousser une noisette de produit dans des mains préalablement humidifiées. Masser délicatement sur l''ensemble du visage humide, puis rincer abondamment à l''eau tiède.',
  100,
  'SKU-ANUA-021',
  149,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  101,
  'La Roche-Posay Cicaplast Baume B5+ 100ml',
  'La Roche-Posay Cicaplast Baume B5+ 100ml + Eau Thermale 50ml Offert',
  'La Roche-Posay Cicaplast Baume B5+ 100ml + Eau Thermale 50ml Offert',
  'La Roche-Posay',
  '/images/cicaplast_bundle.webp',
  '{"/images/cicaplast_bundle.webp"}'::TEXT[],
  179.00,
  199.00,
  'offers',
  '{"visage","offres","baume","apaisant"}'::TEXT[],
  4.9,
  58,
  'Traitement réparateur cutané et apaisant de référence. Sa formule enrichie en Madécassoside, en Cuivre-Zinc-Manganèse purifiants et en Panthénol à 5% accélère la reconstruction de la barrière épidermique. Ce pack exclusif d''officine est accompagné d''un flacon d''Eau Thermale Minéralisante 50ml.',
  'Cicaplast Baume B5+: Aqua, Hydrogenated Polyisobutene, Dimethicone, Glycerin, Butyrospermum Parkii Butter, Panthenol, Centella Asiatica Extract. Eau Thermale: Aqua / Water.',
  'Appliquer deux fois par jour sur une zone cutanée préalablement purifiée et sèche. Vaporiser l''Eau Thermale à tout moment pour calmer l''irritation.',
  100,
  'SKU-LAROCHEPOSAY-101',
  107,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  102,
  'Vichy Capital Soleil Crème Onctueuse SPF 50+ 50ml',
  'Vichy Capital Soleil Crème Onctueuse SPF 50+ 50ml + Sac Plage Offert',
  'Vichy Capital Soleil Crème Onctueuse SPF 50+ 50ml + Sac Plage Offert',
  'Vichy',
  '/images/vichy_sunscreen_bundle.webp',
  '{"/images/vichy_sunscreen_bundle.webp"}'::TEXT[],
  179.00,
  189.00,
  'offers',
  '{"visage","solaire","offres"}'::TEXT[],
  4.8,
  32,
  'Photoprotecteur hydratant onctueux formulé à base d''acide hyaluronique pour les peaux sèches et déshydratées. Protège contre les rayonnements ultraviolets tout en empêchant le dessèchement de la barrière hydrolipidique. Livré dans son coffret avec un élégant sac en matières naturelles.',
  'Aqua/Water, Glycerin, Diisopropyl Sebacate, Ethylhexyl Salicylate, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Sodium Hyaluronate.',
  'Appliquer généreusement sur le visage et le cou avant l''exposition. Renouveler fréquemment après sudation ou friction mécanique.',
  100,
  'SKU-VICHY-101',
  107,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  103,
  'Vichy Dercos Shampooing Energisant Anti-Chute 200ml',
  'Vichy Dercos Shampooing Energisant Anti-Chute 200ml + Format Voyage 50ml Offert',
  'Vichy Dercos Shampooing Energisant Anti-Chute 200ml + Format Voyage 50ml Offert',
  'Vichy',
  '/images/dercos_shampoo_bundle.webp',
  '{"/images/dercos_shampoo_bundle.webp"}'::TEXT[],
  127.00,
  145.00,
  'offers',
  '{"cheveux","anti-chute","offres"}'::TEXT[],
  4.9,
  64,
  'Shampooing dermatologique fortifiant enrichi en Aminexil (molécule brevetée anti-chute) et en vitamines actives B5 et B6. Restructure l''ancrage de la fibre capillaire dans le cuir chevelu pour réduire significativement la casse. Livré avec un format d''officine nomade 50ml.',
  'Aqua/Water, Sodium Laureth Sulfate, Citric Acid, Sodium Hydroxide, Aminexil, Niacinamide, Panthenol, Pyridoxine HCl.',
  'Appliquer sur cheveux humides, masser le cuir chevelu pour activer la circulation, laisser poser 2 minutes pour libérer les actifs, puis rincer.',
  100,
  'SKU-VICHY-103',
  76,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  104,
  'CeraVe Duo Hydratation Intense Baume 454g + Lotion 236ml',
  'CeraVe Duo Hydratation Baume 454g + Lotion 236ml + Trousse Offerte',
  'CeraVe Duo Hydratation Intense Baume 454g + Lotion 236ml',
  'CeraVe',
  'https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  220.00,
  260.00,
  'offers',
  '{"visage","corps","offres","hydratant"}'::TEXT[],
  4.9,
  78,
  'Protocole d''hydratation barrière ultime formulé à base de trois céramides essentiels et d''acide hyaluronique. Ce pack réunit le baume relipidant riche 454g pour les sécheresses intenses et le lait émollient fluide 236ml pour le corps, accompagnés d''une trousse de toilette dermatologique de la marque.',
  'Aqua/Water, Glycerin, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Cetyl Alcohol, Ceteareth-20, Petrolatum, Ceramide NP, Ceramide AP, Ceramide EOP, Phytosphingosine, Cholesterol, Hyaluronic Acid.',
  'Appliquer le Lait Hydratant fluide le matin sur l''ensemble du corps. Appliquer le Baume riche le soir sur les zones les plus sèches pour une réparation nocturne intense.',
  100,
  'SKU-CERAVE-103',
  76,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  105,
  'Garnier Fast Bright Routine Éclat Vitamine C',
  'Garnier Fast Bright Sérum Vitamine C 30ml + Gel Nettoyant 100ml + Masseur Offert',
  'Garnier Fast Bright Routine Éclat Sérum Vitamine C + Gel Nettoyant',
  'Garnier',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  149.00,
  179.00,
  'offers',
  '{"visage","offres","eclat"}'::TEXT[],
  4.8,
  45,
  'Protocole dermo-clarifiant complet comprenant le sérum concentré à la Vitamine C 30ml et le gel nettoyant physiologique 100ml. Cible l''hyperpigmentation et lisse le grain de peau. Incorpore un rouleau de massage facial en quartz naturel pour stimuler le drainage lymphatique.',
  'Aqua/Water, Glycerin, Ascorbic Acid (Vitamine C), Niacinamide, Salicylic Acid, Citrus Limon Fruit Extract, Sodium Hyaluronate.',
  'Purifier le visage matin et soir avec le gel nettoyant. Appliquer ensuite le sérum sur peau humide, puis utiliser le rouleau de massage en mouvements ascendants.',
  100,
  'SKU-GARNIER-105',
  89,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  106,
  'L''Oréal Revitalift Repulpant Sérum 1.5% AH + Crème Jour 50ml',
  'L''Oréal Revitalift Sérum Acide Hyaluronique 30ml + Crème de Jour 50ml + Mini Gua Sha Offert',
  'L''Oréal Revitalift Repulpant Sérum 1.5% AH + Crème Jour 50ml',
  'L''Oréal Paris',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  269.00,
  320.00,
  'offers',
  '{"visage","offres","anti-age"}'::TEXT[],
  4.8,
  52,
  'Protocole combleur anti-rides à base d''acide hyaluronique hautement concentré. Associe le sérum hydratant à 1,5% d''acide hyaluronique pur 30ml et la crème de jour volumisante 50ml. Livré dans son coffret avec un mini Gua Sha en aventurine pour raffermir les muscles faciaux.',
  'Aqua/Water, Glycerin, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Adenosine, Secale Cereale Seed Extract/Rye Seed Extract, Tocopherol.',
  'Appliquer le sérum sur peau humide matin et soir, faire suivre de la crème. Utiliser le Gua Sha en effectuant des massages doux du centre du visage vers les contours extérieurs.',
  100,
  'SKU-LORALPARIS-105',
  89,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  107,
  'Eucerin Sun Oil Control Gel-Crème SPF 50+ 50ml',
  'Eucerin Sun Oil Control SPF 50+ 50ml + Gel Nettoyant 75ml Offert',
  'Eucerin Sun Oil Control Gel-Crème SPF 50+ + Gel Nettoyant 75ml',
  'Eucerin',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  189.00,
  220.00,
  'offers',
  '{"visage","solaire","offres","anti-imperfections"}'::TEXT[],
  4.9,
  67,
  'La très haute protection solaire préférée des peaux mixtes à grasses à tendance acnéique. Offre un effet anti-brillance de 8h. Livré en duo d''officine avec le gel nettoyant purifiant régulateur Dermopure 75ml.',
  'Sun: Aqua, Alcohol Denat., Butyl Methoxydibenzoylmethane, C12-15 Alkyl Benzoate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, L-Carnitine. Gel: Aqua, Sodium Cocoamphoacetate, Propylene Glycol, Citric Acid.',
  'Nettoyer l''épiderme avec le gel Dermopure. Appliquer ensuite le gel-crème photoprotecteur uniformément sur le visage avant de s''exposer.',
  100,
  'SKU-EUCERIN-107',
  113,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  108,
  'Mixa Bébé Douceur Duo Lait Protecteur + Gel Douche',
  'Mixa Bébé Lait Très Doux 250ml + Gel Lavant 250ml + Doudou Offert',
  'Mixa Bébé Douceur Duo Lait Protecteur + Gel Douche Sans Savon',
  'Mixa Bébé',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  119.00,
  149.00,
  'offers',
  '{"corps","bebe","offres","douceur"}'::TEXT[],
  4.9,
  29,
  'Duo d''hygiène et de soin haute tolérance pédiatrique pour la peau très fragile des nouveau-nés. Comprend le lait hydratant protecteur à l''huile d''amande douce 250ml et le gel lavant syndet sans savon cheveux et corps 250ml. Accompagné d''un doudou hypoallergénique.',
  'Lait: Aqua, Paraffinum Liquidum, Glycerin, Prunus Amygdalus Dulcis Oil/Sweet Almond Oil. Gel: Aqua, Sodium Laureth Sulfate, PEG-200 Hydrogenated Glyceryl Palmate, Coco-Betaine.',
  'Utiliser le gel lavant pour l''hygiène quotidienne sous la douche. Hydrater la peau après le bain en appliquant le lait protecteur avec des mouvements d''effleurage doux.',
  100,
  'SKU-MIXABB-107',
  113,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  109,
  'Erborian CC Crème Perfection Teint Centella 45ml',
  'Erborian CC Crème Centella Clair 45ml + Skin Therapy Huile de Nuit 10ml + Pinceau Offert',
  'Erborian CC Crème Perfection Teint Centella + Huile de Nuit 10ml',
  'Erborian',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  389.00,
  450.00,
  'offers',
  '{"visage","maquillage","offres"}'::TEXT[],
  4.7,
  38,
  'Soin perfecteur de teint hybride enrichi en Centella Asiatica répatrice. Cette CC Crème s''adapte à la carnation naturelle pour masquer les rougeurs et sublimer le teint. Livré avec un pinceau applicateur professionnel et l''huile de nuit régénératrice Skin Therapy 10ml.',
  'CC: Aqua/Water, Cyclomethicone, Ethylhexyl Methoxycinnamate, Titanium Dioxide, Centella Asiatica Extract. Huile: Caprylic/Capric Triglyceride, Squalane, Helianthus Annuus Seed Oil.',
  'Appliquer la CC Crème le matin au pinceau ou au doigt. Le soir, appliquer deux à trois gouttes de l''huile régénératrice sur un visage parfaitement propre.',
  100,
  'SKU-ERBORIAN-109',
  233,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  110,
  'Bioderma Sensibio Duo H2O Eau Micellaire 2x500ml',
  'Bioderma Sensibio H2O L''Eau Micellaire 500ml Duo Pack',
  'Bioderma Sensibio Duo H2O Eau Micellaire Dermo-Brevetée 2x500ml',
  'Bioderma',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  179.00,
  238.00,
  'offers',
  '{"visage","offres","demaquillant"}'::TEXT[],
  5,
  145,
  'Solution micellaire physiologique de référence, dermo-brevetée pour les peaux sensibles. Élimine 99% des particules polluantes et des pigments de maquillage tout en respectant l''intégrité de la barrière épidermique. Format d''officine économique en lot exclusif de deux flacons de 500ml.',
  'Aqua/Water/Eau, PEG-6 Caprylic/Capric Glycerides, Fructooligosaccharides, Mannitol, Xylitol, Rhamnose, Cucumis Sativus (Cucumber) Fruit Extract, Propylene Glycol, Cetrimonium Bromide, Disodium EDTA.',
  'Imbiber un coton hydrophile et nettoyer délicatement le visage et le contour des yeux sans frotter. Inutile de rincer.',
  100,
  'SKU-BIODERMA-109',
  233,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  111,
  'Kérastase Genesis Anti-Chute Duo Bain + Masque',
  'Kérastase Genesis Bain Hydra-Fortifiant 250ml + Masque Reconstituant 200ml + Peigne Offert',
  'Kérastase Genesis Anti-Chute Duo Bain + Masque',
  'Kérastase',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  520.00,
  610.00,
  'offers',
  '{"cheveux","anti-chute","offres"}'::TEXT[],
  4.9,
  64,
  'Protocole capillaire fortifiant ciblant la chute de cheveux causée par la casse. Comprend le shampooing physiologique Bain Hydra-Fortifiant 250ml et le masque reconstituant riche 200ml, accompagnés d''un peigne démêlant professionnel.',
  'Bain: Aqua, Sodium Laureth Sulfate, Citric Acid, Cocamidopropyl Betaine. Masque: Aqua, Cetearyl Alcohol, Amodimethicone, Behentrimonium Chloride, Cetyl Esters, Arginine, Centella Asiatica Extract.',
  'Effectuer le lavage avec le Bain sur cheveux humides, émulsionner et rincer. Appliquer ensuite le Masque sur les longueurs essorées, laisser poser 5 minutes, démêler et rincer.',
  100,
  'SKU-KRASTASE-111',
  312,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;
INSERT INTO products (id, title, name, name_fr, vendor, image, images, price, compare_price, category, tags, rating, reviews, description, ingredients, usage, stock, sku, buying_cost, points, status)
VALUES (
  112,
  'SVR Sebiaclear Anti-Acné Active Gel 40ml',
  'SVR Sebiaclear Active Gel 40ml + Eau Micellaire 75ml Offerte',
  'SVR Sebiaclear Anti-Acné Active Gel 40ml',
  'SVR',
  'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop',
  '{"https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?q=80&w=600&auto=format&fit=crop"}'::TEXT[],
  169.00,
  199.00,
  'offers',
  '{"visage","offres","anti-imperfections"}'::TEXT[],
  4.8,
  41,
  'Traitement kératolytique intensif pour peaux acnéiques et sujettes aux imperfections. Formulé avec de la Gluconolactone (14%) et du Niacinamide (4%) pour éliminer boutons et points noirs tout en prévenant les marques rouges. Ce pack comprend l''Eau Micellaire purifiante Sebiaclear 75ml.',
  'Gel: Aqua, Gluconolactone, Alcohol Denat., Niacinamide, Glycerin, Sodium Hydroxide. Eau Micellaire: Aqua, Poloxamer 184, PEG-7 Glyceryl Cocoate, Zinc PCA.',
  'Nettoyer le visage avec l''Eau Micellaire. Appliquer ensuite le Gel Sebiaclear matin et soir sur l''ensemble de la zone cutanée.',
  100,
  'SKU-SVR-111',
  312,
  0,
  'live'
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  name = EXCLUDED.name,
  name_fr = EXCLUDED.name_fr,
  vendor = EXCLUDED.vendor,
  image = EXCLUDED.image,
  images = EXCLUDED.images,
  price = EXCLUDED.price,
  compare_price = EXCLUDED.compare_price,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  description = EXCLUDED.description,
  ingredients = EXCLUDED.ingredients,
  usage = EXCLUDED.usage,
  sku = EXCLUDED.sku,
  buying_cost = EXCLUDED.buying_cost,
  points = EXCLUDED.points;

-- ─── advice articles seed ──────────────────────────────────
INSERT INTO advice_articles (id, slug, title_fr, title_ar, summary_fr, summary_ar, content_fr, content_ar, image, category, read_time, recommended_products, status)
VALUES (
  'art_1',
  'routine-kbeauty-glass-skin',
  'Le Secret du ''Glass Skin'' Coréen : Routine Complète Étape par Étape',
  'سر البشرة الزجاجية الكورية: روتين كامل خطوة بخطوة',
  'Découvrez comment obtenir une peau ultra-lumineuse, lisse et rebondie grâce aux techniques de superposition d''hydratation de la K-Beauty.',
  'اكتشفي كيفية الحصول على بشرة أرق وأكثر مرونة ونضارة باستخدام تقنيات ترطيب البشرة الكورية المتطورة.',
  'La tendance du **Glass Skin** consiste à obtenir une peau si saine, lisse et hydratée qu''elle en devient translucide et lumineuse comme du verre. Ce n''est pas une question de maquillage, mais de santé cutanée.

### Les Étapes Clés de la Routine

1. **Le Double Nettoyage** : Commencez par une huile démaquillante pour dissoudre le sébum, suivie d''un nettoyant aqueux doux pour éliminer les impuretés.
2. **L''Exfoliation Douce** : Utilisez un exfoliant chimique doux (comme les PHA ou l''acide salicylique) 2 à 3 fois par semaine pour lisser le grain de peau.
3. **La Superposition d''Hydratation (7 Skin Method)** : Appliquez plusieurs couches fines de toner hydratant sans alcool pour repulper la peau en profondeur.
4. **L''Essence aux Mucines d''Escargot** : Apportez des nutriments essentiels et favorisez la réparation cutanée avec une essence concentrée.
5. **Le Sérum Éclat** : Un sérum à la niacinamide ou à l''acide hyaluronique pour cibler l''hyperpigmentation et illuminer.
6. **L''Hydratation Scellante** : Une crème barrière pour retenir toute l''hydratation accumulée.
7. **La Protection Solaire (Jour)** : L''étape indispensable pour prévenir le vieillissement prématuré.

Adoptez cette routine quotidiennement pour révéler l''éclat naturel de votre teint !',
  'تعتمد صيحة **البشرة الزجاجية (Glass Skin)** على تحقيق بشرة صحية وناعمة ورطبة للغاية لدرجة أنها تبدو شفافة ومشرقة مثل الزجاج. لا يتعلق الأمر بالمكياج، بل بصحة البشرة الفائقة.

### الخطوات الأساسية للروتين:

1. **التنظيف المزدوج**: ابدئي بـ زيت منظم لإذابة الدهون، يليه غسول مائي لطيف لإزالة الشوائب.
2. **التقشير اللطiff**: استخدمي مقشراً كيميائياً لطيفاً (مثل PHA أو حمض الساليسيليك) مرتين إلى ثلاث مرات في الأسبوع لتنعيم ملمس البشرة.
3. **طبقات الترطيب المتعددة**: ضعي عدة طبقات خfيفة من التونر المرطب الخالي من الكحول لترطيب البشرة بعمق.
4. **إيسنس حلزوني**: غذي بشرتكِ بالمواد الأساسية وعززي إصلاح الخلايا باستخدام خلاصة الحلزون المركزة.
5. **سيروم النضارة**: سيروم النياسيناميد أو حمض الهيالورونيك لاستهداف التصبغات وإضاءة البشرة.
6. **كريم مرطب واقي**: كريم حاجز للبشرة لحبس كل الترطيب المتراكم.
7. **واقي الشمس (نهاراً)**: الخطوة الأهم لحماية البشرة من الشيخوخة المبكرة.

اعتمدي هذا الروتين يومياً لتكشفي عن الإشراق الطبيعي لبشرتكِ!',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&auto=format&fit=crop',
  'kbeauty',
  6,
  '[1,2,3]'::JSONB,
  'published'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title_fr = EXCLUDED.title_fr,
  title_ar = EXCLUDED.title_ar,
  summary_fr = EXCLUDED.summary_fr,
  summary_ar = EXCLUDED.summary_ar,
  content_fr = EXCLUDED.content_fr,
  content_ar = EXCLUDED.content_ar,
  image = EXCLUDED.image,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  recommended_products = EXCLUDED.recommended_products,
  status = EXCLUDED.status;
INSERT INTO advice_articles (id, slug, title_fr, title_ar, summary_fr, summary_ar, content_fr, content_ar, image, category, read_time, recommended_products, status)
VALUES (
  'art_2',
  'combattre-acne-acide-salicylique',
  'Comment l''Acide Salicylique Révolutionne le Traitement de l''Acné',
  'كيف يعالج حمض الساليسيليك حب الشباب ويمنع ظهوره',
  'Comprendre le fonctionnement du BHA pour désobstruer les pores, réguler le sébum et éliminer les imperfections tenaces sans agresser la barrière cutanée.',
  'تعرفي على كيفية عمل BHA لفتح المسام المسدودة وتنظيم إفراز الدهون والتخلص من العيوب دون الإضرار بحاجز البشرة.',
  'L''acide salicylique est un acide bêta-hydroxylé (BHA) liposoluble. Contrairement aux AHA qui travaillent en surface, le BHA pénètre en profondeur dans les pores pour dissoudre l''excès de sébum et les cellules mortes.

### Pourquoi l''utiliser ?
* **Désobstruction des Pores** : Idéal contre les points noirs et microkystes.
* **Régulation du Sébum** : Réduit la brillance de la zone T.
* **Action Anti-inflammatoire** : Calme les rougeurs des boutons actifs.

### Conseils d''Utilisation
Intégrez-le progressivement (1 à 2 fois par semaine au début) le soir, après le nettoyage et avant vos soins hydratants. N''oubliez jamais d''appliquer une protection solaire le lendemain matin car les acides rendent la peau plus sensible au soleil.',
  'حمض الساليسيليك هو حمض بيتا هيدروكسي (BHA) قابل للذوبان في الدهون. على عكس أحماض AHA التي تعمل على السطح، يتغلغل BHA بعمق في المسام لإذابة الدهون الزائدة والخلايا الميتة.

### لماذا يجب استخدامه؟
* **تنظيف المسام**: مثالي لمحاربة الرؤوس السوداء والدهون المتراكمة.
* **تنظيم الدهون**: يقلل من لمعان منطقة الـ T-zone.
* **مضاد للالتهابات**: يهدئ احمرار الحبوب النشطة.

### نصائح الاستخدام:
أدخلي السيروم تدريجياً (مرة إلى مرتين في الأسبوع في البداية) في روتينكِ المسائي, بعد التنظيف وقبل المرطب. لا تنسي تطبيق واقي الشمس في صباح اليوم التالي لأن الأحماض تزيد من حساسية البشرة للشمس.',
  'https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=600&auto=format&fit=crop',
  'skincare',
  4,
  '[4,5]'::JSONB,
  'published'
) ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  title_fr = EXCLUDED.title_fr,
  title_ar = EXCLUDED.title_ar,
  summary_fr = EXCLUDED.summary_fr,
  summary_ar = EXCLUDED.summary_ar,
  content_fr = EXCLUDED.content_fr,
  content_ar = EXCLUDED.content_ar,
  image = EXCLUDED.image,
  category = EXCLUDED.category,
  read_time = EXCLUDED.read_time,
  recommended_products = EXCLUDED.recommended_products,
  status = EXCLUDED.status;

-- ─── code snippets seed ─────────────────────────────────────
INSERT INTO code_snippets (id, name, code, location, active, trigger_type, cron_expression)
VALUES (
  'snip_1',
  'Exemple: Google Analytics & Tag Manager (Mock)',
  '<!-- Global site tag (gtag.js) - Google Analytics -->
<script>
  console.log(''[Mock Google Analytics] Script initialisé.'');
</script>',
  'head',
  true,
  'client',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  code = EXCLUDED.code,
  location = EXCLUDED.location,
  active = EXCLUDED.active,
  trigger_type = EXCLUDED.trigger_type,
  cron_expression = EXCLUDED.cron_expression;
INSERT INTO code_snippets (id, name, code, location, active, trigger_type, cron_expression)
VALUES (
  'snip_2',
  'Exemple: Pixel Facebook (Mock)',
  '<!-- Facebook Pixel Code -->
<script>
  console.log(''[Mock Facebook Pixel] Événement PageView enregistré.'');
</script>',
  'body_start',
  false,
  'client',
  NULL
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  code = EXCLUDED.code,
  location = EXCLUDED.location,
  active = EXCLUDED.active,
  trigger_type = EXCLUDED.trigger_type,
  cron_expression = EXCLUDED.cron_expression;
INSERT INTO code_snippets (id, name, code, location, active, trigger_type, cron_expression)
VALUES (
  'cron_1',
  'Exemple Cron: Archivage Automatique des Logs',
  'console.log(''Début de l\''archivage automatique des logs...'');
// Simulation d''une tâche de maintenance sur la base de données
console.log(''Nettoyage des anciens logs d\''audit terminé avec succès.'');',
  'head',
  true,
  'cron',
  '*/5 * * * *'
) ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  code = EXCLUDED.code,
  location = EXCLUDED.location,
  active = EXCLUDED.active,
  trigger_type = EXCLUDED.trigger_type,
  cron_expression = EXCLUDED.cron_expression;
